---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:

- name: gradle-build
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/openjdk11:v11.0.5_10
  commands:
  - ./gradlew build --max-workers 1
  when:
    event:
    - push
    - pull_request

- name: update-semver
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/docker-openjdk8-git:v1.5.0
  commands:
  - sh /root/git-utilities/set-up-github-user.sh "$${GITHUB_SSH_KEY}"
  - ./gradlew release -Prelease.useAutomaticVersion=true -x runBuildTasks
  - git describe --abbrev=0 --tags > ./tagSemver
  environment:
    GITHUB_SSH_KEY:
      from_secret: github_ssh_key
  when:
    branch:
    - master
    event:
    - push

- name: ensure-dind-ready
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  when:
    event:
      - push

- name: docker-build-tag-and-push
  image: plugins/docker
  commands: export SEMVER=$(cat ./tagSemver)
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/pttg-ip-audit
    dockerfile: ./Dockerfile.acp
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
      - build-${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_USERNAME: ukhomeofficedigital+pttg
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    branch:
      - master
    event:
      - push

- name: docker-semver-tag
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
    - docker tag pttg-ip-audit quay.io/ukhomeofficedigital/pttg-ip-audit:$(cat ./tagSemver)
    - docker push quay.io/ukhomeofficedigital/pttg-ip-audit:$$(cat ./tagSemver)
  environment:
    DOCKER_USERNAME: ukhomeofficedigital+pttg
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    branch:
      - master
    event:
      - push


- name: docker-build-tag-and-push_feature-branch
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/pttg-ip-audit
    dockerfile: ./Dockerfile.acp
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BRANCH}
  environment:
    DOCKER_USERNAME: ukhomeofficedigital+pttg
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    branch:
      exclude:
        - master
    event:
      - push


#- name: trigger-e2e-tests
#  pull: if-not-exists
#  image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
#  settings:
#    branch: master
#    drone_server: https://drone.acp.homeoffice.gov.uk
#    repo: UKHomeOffice/pttg-ip-e2e-tests
#  environment:
#    DRONE_TOKEN:
#      from_secret: DRONE_TOKEN
#  when:
#    branch:
#    - master
#    event:
#    - push

- name: clone-kube-project
  pull: if-not-exists
  image: plugins/git
  commands:
  - git clone https://github.com/UKHomeOffice/kube-pttg-ip-audit.git
  when:
    event:
    - push
    - tag
    - promote

- name: deploy-to-dev-from-build-number
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.17.0
  commands:
  - cd kube-pttg-ip-audit
  - ./deploy.sh
  environment:
    ENVIRONMENT: dev
    KUBE_NAMESPACE: pttg-ip-dev
    KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    PTTG_IP_DEV:
      from_secret: pttg_ip_dev
    IMAGE_VERSION: build-${DRONE_BUILD_NUMBER}
  when:
    branch:
    - master
    event:
    - push

- name: deployment-to-non-prod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.17.0
  commands:
  - cd kube-pttg-ip-audit
  - ./deploy.sh
  environment:
    ENVIRONMENT: ${DRONE_DEPLOY_TO}
    KUBE_NAMESPACE: pttg-ip-${DRONE_DEPLOY_TO}
    KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    PTTG_IP_DEV:
      from_secret: pttg_ip_dev
  when:
    event:
    - promote
    target:
    - dev
    - test
    - preprod

- name: deploy-to-prod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.17.0
  commands:
  - cd kube-pttg-ip-audit
  - ./deploy.sh
  environment:
    ENVIRONMENT: ${DRONE_DEPLOY_TO}
    KUBE_NAMESPACE: pttg-ip-${DRONE_DEPLOY_TO}
    KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
    PTTG_IP_PR:
      from_secret: pttg_ip_pr
  when:
    event:
    - promote
    target:
    - pr

services:
  - name: docker-in-docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
