package uk.gov.digital.ho.pttg;

public enum AuditEventType {

    HMRC_INCOME_REQUEST,

    INCOME_PROVING_FINANCIAL_STATUS_REQUEST,
    INCOME_PROVING_FINANCIAL_STATUS_RESPONSE,

    INCOME_PROVING_INCOME_CHECK_REQUEST,
    INCOME_PROVING_INCOME_CHECK_RESPONSE,

    RESIDENCE_PROVING_EMPLOYMENT_STATUS_REQUEST,
    RESIDENCE_PROVING_EMPLOYMENT_STATUS_RESPONSE,
}
